import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { storage } from './storage';
import type { Gig, Expense, User } from '@shared/schema';

interface ReportOptions {
  userId: number;
  period: 'monthly' | 'annual';
  year: number;
  month?: number;
}

interface ReportData {
  user: User;
  gigs: Gig[];
  expenses: Expense[];
  period: string;
  totalIncome: number;
  totalExpenses: number;
  totalMileage: number;
  mileageValue: number;
  netIncome: number;
}

export class PDFReportGenerator {
  private doc: jsPDF;
  private pageNumber: number = 1;

  constructor() {
    this.doc = new jsPDF();
  }

  async generateReport(options: ReportOptions): Promise<Buffer> {
    const reportData = await this.prepareReportData(options);
    
    this.addCoverPage(reportData);
    this.addIncomeSummary(reportData);
    this.addExpenseSummary(reportData);
    this.addMileageLog(reportData);
    this.addSummaryTotals(reportData);
    this.addFooter();

    return Buffer.from(this.doc.output('arraybuffer'));
  }

  private async prepareReportData(options: ReportOptions): Promise<ReportData> {
    const user = await storage.getUser(options.userId);
    if (!user) throw new Error('User not found');

    const startDate = options.period === 'monthly' 
      ? new Date(options.year, options.month! - 1, 1)
      : new Date(options.year, 0, 1);
    
    const endDate = options.period === 'monthly'
      ? new Date(options.year, options.month!, 0)
      : new Date(options.year, 11, 31);

    const gigs = await storage.getGigsByDateRange(
      options.userId,
      startDate.toISOString().split('T')[0],
      endDate.toISOString().split('T')[0]
    );

    const expenses = await storage.getExpensesByDateRange(
      options.userId,
      startDate.toISOString().split('T')[0],
      endDate.toISOString().split('T')[0]
    );

    // Calculate totals
    const completedGigs = gigs.filter(g => g.status === 'completed');
    const totalIncome = completedGigs.reduce((sum, gig) => {
      const actualPay = parseFloat(gig.actualPay || '0');
      const tips = parseFloat(gig.tips || '0');
      return sum + actualPay + tips;
    }, 0);

    const totalExpenses = expenses.reduce((sum, expense) => {
      return sum + parseFloat(expense.amount || '0');
    }, 0);

    const gigExpenses = gigs.reduce((sum, gig) => {
      const parking = parseFloat(gig.parkingExpense || '0');
      const other = parseFloat(gig.otherExpenses || '0');
      return sum + parking + other;
    }, 0);

    const totalMileage = gigs.reduce((sum, gig) => sum + (gig.mileage || 0), 0);
    const mileageValue = totalMileage * 0.67; // Standard mileage rate

    const netIncome = totalIncome - (totalExpenses + gigExpenses + mileageValue);

    const periodStr = options.period === 'monthly' 
      ? `${new Date(options.year, options.month! - 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`
      : `${options.year} Annual Report`;

    return {
      user,
      gigs: completedGigs,
      expenses,
      period: periodStr,
      totalIncome,
      totalExpenses: totalExpenses + gigExpenses,
      totalMileage,
      mileageValue,
      netIncome
    };
  }

  private addCoverPage(data: ReportData): void {
    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('FREELANCER INCOME REPORT', 105, 60, { align: 'center' });

    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(data.user.name || 'Business Name', 105, 80, { align: 'center' });

    this.doc.setFontSize(14);
    this.doc.text(data.period, 105, 100, { align: 'center' });

    this.doc.setFontSize(12);
    this.doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 120, { align: 'center' });

    if (data.user.email) {
      this.doc.text(`Contact: ${data.user.email}`, 105, 140, { align: 'center' });
    }

    this.doc.setFontSize(10);
    this.doc.text('This report is generated by Giggy for informational use only and does not constitute tax advice.', 105, 260, { align: 'center' });

    this.addPageNumber();
    this.doc.addPage();
    this.pageNumber++;
  }

  private addIncomeSummary(data: ReportData): void {
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('💰 INCOME SUMMARY', 20, 30);

    const tableData = data.gigs.map(gig => [
      new Date(gig.date).toLocaleDateString(),
      gig.clientName || 'Direct Client',
      gig.gigType || 'Service',
      `$${(parseFloat(gig.actualPay || '0') + parseFloat(gig.tips || '0')).toFixed(2)}`
    ]);

    (this.doc as any).autoTable({
      head: [['Date', 'Source', 'Gig Type', 'Amount']],
      body: tableData,
      startY: 40,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] },
      foot: [['', '', 'TOTAL', `$${data.totalIncome.toFixed(2)}`]],
      footStyles: { fillColor: [241, 241, 241], fontStyle: 'bold' }
    });

    this.addPageNumber();
    this.doc.addPage();
    this.pageNumber++;
  }

  private addExpenseSummary(data: ReportData): void {
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('🧾 EXPENSE SUMMARY', 20, 30);

    const expenseData: string[][] = [];
    
    // Add regular expenses
    data.expenses.forEach(expense => {
      expenseData.push([
        new Date(expense.date).toLocaleDateString(),
        'Various',
        expense.category || 'Business',
        expense.description || '',
        `$${parseFloat(expense.amount || '0').toFixed(2)}`
      ]);
    });

    // Add gig-related expenses
    data.gigs.forEach(gig => {
      const parking = parseFloat(gig.parkingExpense || '0');
      const other = parseFloat(gig.otherExpenses || '0');
      
      if (parking > 0) {
        expenseData.push([
          new Date(gig.date).toLocaleDateString(),
          'Parking',
          'Travel',
          `${gig.eventName || 'Gig'} - Parking`,
          `$${parking.toFixed(2)}`
        ]);
      }
      
      if (other > 0) {
        expenseData.push([
          new Date(gig.date).toLocaleDateString(),
          'Various',
          'Business',
          `${gig.eventName || 'Gig'} - Other expenses`,
          `$${other.toFixed(2)}`
        ]);
      }
    });

    (this.doc as any).autoTable({
      head: [['Date', 'Vendor', 'Category', 'Description', 'Amount']],
      body: expenseData,
      startY: 40,
      theme: 'grid',
      headStyles: { fillColor: [231, 76, 60] },
      foot: [['', '', '', 'TOTAL', `$${data.totalExpenses.toFixed(2)}`]],
      footStyles: { fillColor: [241, 241, 241], fontStyle: 'bold' }
    });

    this.addPageNumber();
    this.doc.addPage();
    this.pageNumber++;
  }

  private addMileageLog(data: ReportData): void {
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('🚗 MILEAGE LOG', 20, 30);

    const mileageData = data.gigs
      .filter(gig => gig.mileage && gig.mileage > 0)
      .map(gig => [
        new Date(gig.date).toLocaleDateString(),
        `${gig.eventName || 'Gig'} (${gig.clientName || 'Client'})`,
        gig.gigAddress || 'Home',
        gig.gigAddress || 'Destination',
        gig.mileage?.toString() || '0',
        '$0.67/mi',
        `$${((gig.mileage || 0) * 0.67).toFixed(2)}`
      ]);

    (this.doc as any).autoTable({
      head: [['Date', 'Purpose', 'Start Address', 'End Address', 'Miles', 'Rate', 'Total Value']],
      body: mileageData,
      startY: 40,
      theme: 'grid',
      headStyles: { fillColor: [46, 204, 113] },
      foot: [['', '', '', '', data.totalMileage.toString(), '', `$${data.mileageValue.toFixed(2)}`]],
      footStyles: { fillColor: [241, 241, 241], fontStyle: 'bold' }
    });

    this.addPageNumber();
    this.doc.addPage();
    this.pageNumber++;
  }

  private addSummaryTotals(data: ReportData): void {
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('📊 SUMMARY TOTALS', 20, 30);

    const summaryData = [
      ['Total Income', `$${data.totalIncome.toFixed(2)}`],
      ['Total Expenses', `$${data.totalExpenses.toFixed(2)}`],
      ['Total Mileage', `${data.totalMileage} miles`],
      ['Mileage Value', `$${data.mileageValue.toFixed(2)}`],
      ['Net Income', `$${data.netIncome.toFixed(2)}`]
    ];

    (this.doc as any).autoTable({
      head: [['Category', 'Total']],
      body: summaryData,
      startY: 40,
      theme: 'grid',
      headStyles: { fillColor: [52, 73, 94] },
      columnStyles: {
        1: { fontStyle: 'bold', halign: 'right' }
      }
    });

    this.addPageNumber();
  }

  private addFooter(): void {
    const pageCount = this.doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(`Page ${i} of ${pageCount}`, 195, 285, { align: 'right' });
    }
  }

  private addPageNumber(): void {
    this.doc.setFontSize(8);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`Page ${this.pageNumber}`, 195, 285, { align: 'right' });
  }
}